
# Uploading and exploring the dataset ---------------------------------------------------

cyst <- read.csv(file="Data/cyst_bias_study.csv", header=TRUE, sep=";")


# Investigate prior distribution ------------------------------------------

# Find the equivalent of a OR of 2 on the log scale to set mu for the prior for the coefficient
mu_betaquest <- round(log(2), digits=3)
mu_betaquest
# OK so we need a prior distribution with a mu of 0.693 for betaquest's coefficient 

#You could pick any value for the inverse variance. I chose to use an inverse variance of 5 (equivalent to a variance of 0.2 or to a SD of 0.45) 
inv_var_betaquest <- 5

# It would look like this:
SD_betaquest <- sqrt(1/inv_var_betaquest)
curve(dnorm(x, mean=mu_betaquest, sd=SD_betaquest),                                    
      from=-3, to=3,                                                 
      main="Normal distribution with mean of 0.693 and inverse variance of 5",     
      xlab = "Value", ylab = "Density")

# If we compare with that of Question 2 (the unif(-2.996, 2.996)):
curve(dnorm(x, mean=mu_betaquest, sd=SD_betaquest),                                    
      from=-4, to=4,                                                 
      xlab = "Value", ylab = "Density")
curve(dunif(x, min=low.betaquest, max=hi.betaquest),                                    
      xlab = "Value", ylab = "Density", lty=2, add=TRUE)


# Run a conventional logistic regression model ----------------------------

#I need to create R objects that will be used in the model text file to describe the priors for the intercept (the ones for the coefficient are already done)
options(scipen=999) # To avoid use of scientific notation by R
mu_int <- 0.0         #mu for the intercept    
inv_var_int <- 0.0001 #Inverse variance for the intercept


#I need a R object that will be used in the model text file for the number of observations
a <- dim(cyst)
num_obs <- a[1] 
num_obs

#I need a text file where the model is written using the R object previously created
model_inform_plus <- paste0("model{
      #===	LIKELIHOOD	===#
			for( i in 1 : ",num_obs," ) {
							test[i] ~ dbern(p[i])
							logit(p[i]) <- int + betaquest*quest[i]  
			}
			
      #===   EXTRA CALCULATION TO GET OR ===#
			ORquest <- exp(betaquest)
			
      #===	PRIOR	===#		
			int ~ dnorm(",mu_int,", ",inv_var_int,")
			betaquest ~ dnorm(",mu_betaquest,", ",inv_var_betaquest,")
			}")

write.table(model_inform_plus, file="model_inform_plus.txt", quote=FALSE, sep="", row.names=FALSE,
            col.names=FALSE)

#Now I need a number of sets of initial values corresponding to the number of Markov chains that will be ran. I plan to use 3 chains, thus 3 sets of initial values
#Initializing values for 3 chains
inits <- list(
  list(int=0.0, betaquest=0.0),
  list(int=1.0, betaquest=1.0),
  list(int=-1.0, betaquest=-1.0)
)

# We have everything, we can now run the model using R2OpenBUGS
library(R2OpenBUGS)
#Set number of iterations
niterations <- 5000
#Run the Bayesian model
bug.out.inform_plus <- bugs(data=cyst, 
                inits=inits, 
                parameters.to.save=c("int", "betaquest", "ORquest"),
                n.iter=niterations, 
                n.burnin=0, 
                n.thin=1,
                n.chains=3, 
                model.file="model_inform_plus.txt", 
                debug=TRUE,
                DIC=FALSE)


# MCMC diagnostic ---------------------------------------------------------

# I need to generate the diagnostic plots for the MCMC 
library(mcmcplots)
bug.mcmc <- as.mcmc(bug.out.inform_plus)
mcmcplot(bug.mcmc, title="Diagnostic plots")
effectiveSize(bug.mcmc)

# Applying burn in ---------------------------------

# Now we need to set up a burn in period and discard values generated by the MCMC during this period
# Set burn-in to 1000
burnin <- 1000
# Create a sequence of values from 1st post-burn in value to last one.
k <- seq(from=(burnin+1), to=niterations, by=1)
# Combine chains post-burn in
estimates_conv_inform_plus <- data.frame(rbind(bug.out.inform_plus$sims.array[k,1,],bug.out.inform_plus$sims.array[k,2,],bug.out.inform_plus$sims.array[k,3,]))


# Summarizing results -----------------------------------------------------

# We can now summarized the MCMC results (median, percentiles 2.5th and 97.5th)
# medians and 95% credible intervals
res_conv_inform_plus <- round(
  t(
    apply(X=estimates_conv_inform_plus, MARGIN=2, FUN=quantile, probs=c(0.5, 0.025, 0.975))
  ), 
  digits=3)
res_conv_inform_plus

# You could also plot the prior and posterior distributions. Here I also included the posterior distribution from the vague model (blue dashed line) 
# and of the preceding informative model (grey dashed line)

# Posterior distribution
std <- sqrt(1/inv_var_betaquest)
plot(density(x=estimates_conv_inform_plus$betaquest), 
     main="Quest coefficient",
     xlab="Value", ylab="Density",
     xlim=c(-2, 3) 
)
# Posterior distribution of the preceding informative model
lines(density(estimates_conv_inform$betaquest), lty=2, col="grey")
# Posterior distribution of the vague model
lines(density(estimates_conv_vague$betaquest), lty=2, col="blue")
# Prior distribution
curve(dnorm(x, 
            mean=(mu_betaquest), 
            sd=std
),
lty=2,
col="red",
add=TRUE
)
