
# Uploading and exploring the dataset ---------------------------------------------------

cyst_reduced <- read.csv(file="Data/cyst_bias_study_reduced.csv", header=TRUE, sep=";")

#Checking number of variables and observations
dim(cyst_reduced)

# Checking the first 6 lines
head(cyst_reduced)  

# Exploring the quest and test variables
table(cyst_reduced$test)

table(cyst_reduced$quest)

# Creating a 2 by 2 table
tab <- table(cyst_reduced$quest,cyst_reduced$test)
# Reordering the values in the 2x2 table to fit epi.2by2() expected data presentation (D+E+, D+E-, D-E+, D-E-)
tab2<- tab[c(2,1),c(2,1)]
# Checking crude associations
library(epiR)
epi.2by2(tab2, method="cohort.count")


# Run a conventional logistic regression model with vague priors----------------------------

#I need to create R objects that will be used in the model text file to describe the priors
options(scipen=999)
mu_int <- 0.0             
inv_var_int <- 0.0001 
mu_betaquest <- 0.0
inv_var_betaquest <- 0.0001

#I need a R object that will be used in the model text file for the number of observations
a <- dim(cyst_reduced)
num_obs <- a[1] 
num_obs

#I need a text file where the model is written using the R object previously created
model_vague_redu <- paste0("model{
      #===	LIKELIHOOD	===#
			for( i in 1 : ",num_obs," ) {
							test[i] ~ dbern(p[i])
							logit(p[i]) <- int + betaquest*quest[i]  
			}
			
      #===   EXTRA CALCULATION TO GET OR ===#
			ORquest <- exp(betaquest)
			
      #===	PRIOR	===#		
			int ~ dnorm(",mu_int,", ",inv_var_int,")
			betaquest ~ dnorm(",mu_betaquest,", ",inv_var_betaquest,")
			}")

write.table(model_vague_redu, file="model_vague_redu.txt", quote=FALSE, sep="", row.names=FALSE,
            col.names=FALSE)

#Now I need a number of sets of initial values corresponding to the number of Markov chains that will be ran. I plan to use 3 chains, thus 3 sets of initial values
#Initializing values for 3 chains
inits <- list(
  list(int=0.0, betaquest=0.0),
  list(int=1.0, betaquest=1.0),
  list(int=-1.0, betaquest=-1.0)
)

# We have everything, we can now run the model using R2OpenBUGS
library(R2OpenBUGS)
#Set number of iterations
niterations <- 5000
#Run the Bayesian model
bug.out.vague_redu <- bugs(data=cyst_reduced, 
                                 inits=inits, 
                                 parameters.to.save=c("int", "betaquest", "ORquest"),
                                 n.iter=niterations, 
                                 n.burnin=0, 
                                 n.thin=1,
                                 n.chains=3, 
                                 model.file="model_vague_redu.txt", 
                                 debug=TRUE)


# MCMC diagnostic ---------------------------------------------------------

# I need to generate the diagnostic plots for the MCMC 
library(mcmcplots)
bug.mcmc <- as.mcmc(bug.out.vague_redu)
mcmcplot(bug.mcmc, title="Diagnostic plots")


# Applying burn in ---------------------------------

# Now we need to set up a burn in period and discard values generated by the MCMC during this period
# Set burn-in to 1000
burnin <- 1000
# Create a sequence of values from 1st post-burn in value to last one.
k <- seq(from=(burnin+1), to=niterations, by=1)
# Combine chains post-burn in
estimates_conv_vague_redu <- data.frame(rbind(bug.out.vague_redu$sims.array[k,1,],bug.out.vague_redu$sims.array[k,2,],bug.out.vague_redu$sims.array[k,3,]))


# Summarizing results -----------------------------------------------------

# We can now summarized the MCMC results (median, percentiles 2.5th and 97.5th)
# medians and 95% credible intervals
res_conv_vague_redu <- round(
  t(
    apply(X=estimates_conv_vague_redu, MARGIN=2, FUN=quantile, probs=c(0.5, 0.025, 0.975))
  ), 
  digits=3)
res_conv_vague_redu


# Run a conventional logistic regression model with informative priors----------------------------

#I need to create R objects that will be used in the model text file to describe the priors
options(scipen=999)
mu_betaquest <- round(log(2), digits=3)
inv_var_betaquest <- 5

#I need a text file where the model is written using the R object previously created
model_inform_plus_redu <- paste0("model{
      #===	LIKELIHOOD	===#
			for( i in 1 : ",num_obs," ) {
							test[i] ~ dbern(p[i])
							logit(p[i]) <- int + betaquest*quest[i]  
			}
			
      #===   EXTRA CALCULATION TO GET OR ===#
			ORquest <- exp(betaquest)
			
      #===	PRIOR	===#		
			int ~ dnorm(",mu_int,", ",inv_var_int,")
			betaquest ~ dnorm(",mu_betaquest,", ",inv_var_betaquest,")
			}")

write.table(model_inform_plus_redu, file="model_inform_plus_redu.txt", quote=FALSE, sep="", row.names=FALSE,
            col.names=FALSE)


# We have everything, we can now run the model using R2OpenBUGS
library(R2OpenBUGS)
#Set number of iterations
niterations <- 5000
#Run the Bayesian model
bug.out.inform_plus_redu <- bugs(data=cyst_reduced, 
                                 inits=inits, 
                                 parameters.to.save=c("int", "betaquest", "ORquest"),
                                 n.iter=niterations, 
                                 n.burnin=0, 
                                 n.thin=1,
                                 n.chains=3, 
                                 model.file="model_inform_plus_redu.txt", 
                                 debug=TRUE,
                                 DIC=FALSE)


# MCMC diagnostic ---------------------------------------------------------

# I need to generate the diagnostic plots for the MCMC 
library(mcmcplots)
bug.mcmc <- as.mcmc(bug.out.inform_plus_redu)
mcmcplot(bug.mcmc, title="Diagnostic plots")
effectiveSize(bug.mcmc)

# Applying burn in ---------------------------------

# Now we need to set up a burn in period and discard values generated by the MCMC during this period
# Set burn-in to 1000
burnin <- 1000
# Create a sequence of values from 1st post-burn in value to last one.
k <- seq(from=(burnin+1), to=niterations, by=1)
# Combine chains post-burn in
estimates_conv_inform_plus_redu <- data.frame(rbind(bug.out.inform_plus_redu$sims.array[k,1,],bug.out.inform_plus_redu$sims.array[k,2,],bug.out.inform_plus_redu$sims.array[k,3,]))


# Summarizing results -----------------------------------------------------

# We can now summarized the MCMC results (median, percentiles 2.5th and 97.5th)
# medians and 95% credible intervals
res_conv_inform_plus_redu <- round(
  t(
    apply(X=estimates_conv_inform_plus_redu, MARGIN=2, FUN=quantile, probs=c(0.5, 0.025, 0.975))
  ), 
  digits=3)
res_conv_inform_plus_redu

# You could also plot the prior and posterior distributions. Here I also included the posterior distribution from the vague model (blue line) 
# and of the preceding informative model (grey dashed line)

# Posterior distribution
std <- sqrt(1/inv_var_betaquest)
plot(density(x=estimates_conv_inform_plus_redu$betaquest), 
     main="Quest coefficient",
     xlab="Value", ylab="Density",
     xlim=c(-2, 3) 
)
# Posterior distribution of the vague model
lines(density(estimates_conv_vague_redu$betaquest), col="blue")
# Prior distribution
curve(dnorm(x, 
            mean=(mu_betaquest), 
            sd=std
),
lty=2,
col="red",
add=TRUE
)
