# Uploading and exploring the dataset ---------------------------------------------------
cyst <- read.csv(file="Data/cyst_bias_study.csv", header=TRUE, sep=";")


# Investigate prior distribution ------------------------------------------

# Find the equivalent of a OR of 0.05 and of 20 on the log scale to set prior for the coefficient
low.betaquest <- round(log(0.05), digits=3)
low.betaquest
hi.betaquest <- round(log(20), digits=3)
hi.betaquest
# OK so we need a prior distribution bounded at approximately -2.996 to +2.996 for betaquest's coefficient 

# It would look like this:
curve(dunif(x, min=low.betaquest, max=hi.betaquest),                                    
      from=-10, to=10,                                                 
      main="Uniform distribution with -3.0 and 3.0 limits",    
      xlab = "Value", ylab = "Density") 


# Run a conventional logistic regression model ----------------------------

#I need to create R objects that will be used in the model text file to describe the priors
options(scipen=999) # To avoid use of scientific notation by R
mu_int <- 0.0         #mu for the intercept    
inv_var_int <- 0.0001 #Inverse variance for the intercept

#I need a R object that will be used in the model text file for the number of observations
a <- dim(cyst)
num_obs <- a[1] 
num_obs

#I need a text file where the model is written using the R object previously created
model_inform <- paste0("model{
      #===	LIKELIHOOD	===#
			for( i in 1 : ",num_obs," ) {
							test[i] ~ dbern(p[i])
							logit(p[i]) <- int + betaquest*quest[i]  
			}
			
      #===   EXTRA CALCULATION TO GET OR ===#
			ORquest <- exp(betaquest)
			
      #===	PRIOR	===#		
			int ~ dnorm(",mu_int,", ",inv_var_int,")
			betaquest ~ dunif(",low.betaquest,", ",hi.betaquest,")
			}")

write.table(model_inform, file="model_inform.txt", quote=FALSE, sep="", row.names=FALSE,
            col.names=FALSE)

#Now I need a number of sets of initial values corresponding to the number of Markov chains that will be ran. I plan to use 3 chains, thus 3 sets of initial values
#Initializing values for 3 chains
inits <- list(
  list(int=0.0, betaquest=0.0),
  list(int=1.0, betaquest=1.0),
  list(int=-1.0, betaquest=-1.0)
)

# We have everything, we can now run the model using R2OpenBUGS
library(R2OpenBUGS)
#Set number of iterations
niterations <- 5000
#Run the Bayesian model
bug.out.inform <- bugs(data=cyst, 
                inits=inits, 
                parameters.to.save=c("int", "betaquest", "ORquest"),
                n.iter=niterations, 
                n.burnin=0, 
                n.thin=1,
                n.chains=3, 
                model.file="model_inform.txt", 
                debug=TRUE,
                DIC=FALSE)

# MCMC diagnostic ---------------------------------------------------------

# I need to generate the diagnostic plots for the MCMC 
library(mcmcplots)
bug.mcmc <- as.mcmc(bug.out.inform)
mcmcplot(bug.mcmc, title="Diagnostic plots")
effectiveSize(bug.mcmc)

# Applying burn in ---------------------------------

# Now we need to set up a burn in period and discard values generated by the MCMC during this period
# Set burn-in to 1000
burnin <- 1000
# Create a sequence of values from 1st post-burn in value to last one.
k <- seq(from=(burnin+1), to=niterations, by=1)
# Combine chains post-burn in
estimates_conv_inform <- data.frame(rbind(bug.out.inform$sims.array[k,1,],bug.out.inform$sims.array[k,2,],bug.out.inform$sims.array[k,3,]))

# Summarizing results -----------------------------------------------------

# We can now summarized the MCMC results (median, percentiles 2.5th and 97.5th)
# medians and 95% credible intervals
res_conv_inform <- round(
  t(
    apply(X=estimates_conv_inform, MARGIN=2, FUN=quantile, probs=c(0.5, 0.025, 0.975))
  ), 
  digits=3)
res_conv_inform

# You could also plot the posterior distributions, though it is not mandatory at all. The figure will show up in the Plots panel (lower right panel in RStudio )
plot(density(x=estimates_conv_inform$betaquest), 
     main="Quest coefficient",
     xlab="Value", ylab="Density",
     xlim=c(-4, 4) # I had to broaden the limits of the x axis (from -4 to +4) so we can actually "see" the prior distribution
)
curve(dunif(x, min=low.betaquest, max=hi.betaquest
),
lty=2,
col="red",
add=TRUE
)


